name: Build with JDK 7

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: openjdk:7-jdk

    steps:
    - uses: actions/checkout@v3

    - name: Install Ant
      run: apt-get update && apt-get install -y ant

    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
